# Quick test config with just ZIC agents
CONFIG = {
    "experiment_name": "test_quick_zic",
    "num_rounds": 10,
    "num_periods": 2,
    "steps_per_period": 10,
    "train_rounds": 0,
    
    "num_buyers": 3,
    "num_sellers": 3,
    "num_tokens": 2,
    "min_price": 50,
    "max_price": 250,
    "gametype": 453,
    
    "buyers": [{"type": "zic"}] * 3,
    "sellers": [{"type": "zic"}] * 3,
    
    "rl_params": {
        "learning_rate": 0.0003,
        "batch_size": 512,
        "n_epochs": 10,
        "gamma": 0.99,
        "gae_lambda": 0.95,
        "clip_epsilon": 0.2,
        "value_loss_coef": 0.5,
        "entropy_coef": 0.01,
        "max_grad_norm": 0.5,
        "nn_hidden_layers": [64],
        "num_price_actions": 21,
        "price_range_pct": 0.15,
        "use_reward_scaling": False,
        "lstm_hidden_size": 32,
        "lstm_num_layers": 1,
        "log_level_rl": "WARNING",
        "log_training_stats": False,
    },
    
    "rng_seed_values": 42,
    "rng_seed_auction": 43,
    "rng_seed_rl": 44,
    "log_level": "WARNING",
    "log_to_file": False,
    "save_detailed_stats": False,
    "save_rl_model": False,
    "generate_per_round_plots": False,
    "generate_eval_behavior_plots": False,
}