# @package _global_
#
# Experiment 2.3: PPO vs Agent Zoo (Generalization Test)
#
# Goal: Test whether PPO can generalize to diverse opponents (ZIC, Kaplan, ZIP, GD)
# after curriculum training.
#
# Expected outcome: PPO maintains profitability against heterogeneous population,
# demonstrating it hasn't overfit to any single opponent type.
#
# Prerequisite: Load checkpoint from Experiment 2.2 (PPO vs Kaplan)

defaults:
  - /rl/ppo
  - /rl/vectorization
  - /rl/training

# Experiment metadata
experiment:
  name: "2_3_ppo_vs_zoo"
  description: "PPO generalization test against mixed opponent population"
  phase: "4.3"
  task: "Evaluate PPO against agent zoo (ZIC, Kaplan, ZIP, GD)"
  prerequisite: "2_2_ppo_vs_kaplan (load pretrained weights)"

# Training configuration (short fine-tuning run)
training:
  total_timesteps: 500_000  # Shorter - mainly evaluation

  # W&B logging
  wandb:
    enabled: true
    name: "ppo_vs_zoo_generalization"
    tags: ["ppo", "mixed-opponents", "generalization", "phase-4.3", "zoo-test"]
    notes: |
      Experiment 2.3: PPO tested against diverse opponent mix.
      Success metric: PPO remains profitable vs all opponent types.
      Tests for overfitting - PPO should generalize beyond ZIC/Kaplan.

# Environment configuration with mixed opponents
vectorization:
  env:
    num_buyers: 5
    num_sellers: 5
    num_tokens_per_agent: 3
    max_timesteps: 100
    price_min: 0
    price_max: 100
    rl_agent_type: "buyer"
    opponent_type: "Mixed"  # Random mix of ZIC, Kaplan, ZIP, GD
    seed: 42

    # Mixed opponent configuration (requires implementation)
    # Opponent distribution: 40% ZIC, 30% Kaplan, 20% ZIP, 10% GD
    mixed_opponent_config:
      enabled: true
      distribution:
        ZIC: 0.4
        Kaplan: 0.3
        ZIP: 0.2
        GD: 0.1

# PPO configuration with checkpoint loading
ppo:
  # Load pretrained model from Stage 2
  load_checkpoint: "./checkpoints/2_2_ppo_vs_kaplan/final_model.zip"

  # Lower learning rate for fine-tuning
  learning_rate: 0.00003  # Very low LR - mostly evaluation
